server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service  # ??????ID
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: admin-service # ????????ID
          uri: http://localhost:8082
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1