server:
  port: 8848

# Spring??
spring:
  # ?????
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:Wzy20041224!}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:summer2025_dev}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true