server:
  port: 8082

spring:
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:Wzy20041224!}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:summer2025}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

mybatis-plus:
  interceptor:
    optimistic-lock: true
    show-sql: true

jwt:
  secret-key: "b9f8e7d6c5a4b3f2e1d0c9b8a7f6e5d4"

